# Generated by Django 5.1.6 on 2025-02-08 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='subscription_link',
            field=models.CharField(blank=True, max_length=500, unique=True),
        ),
    ]
