# Generated by Django 5.1.6 on 2025-02-08 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_brand_subscription_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('newsletter_id', models.CharField(editable=False, max_length=20, unique=True)),
                ('thumbnail', models.ImageField(upload_to='thumbnails/')),
                ('xml_template', models.FileField(upload_to='xml_templates/')),
            ],
        ),
    ]
