# Generated by Django 5.1.6 on 2025-02-11 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_subscriber'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriber',
            name='subscriber_id',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
