# Generated by Django 5.1.6 on 2025-02-11 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_subscriber_subscriber_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaign',
            name='newsletter',
        ),
        migrations.AlterField(
            model_name='campaign',
            name='campaign_id',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
