# Generated by Django 5.1.6 on 2025-02-11 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_remove_subscriber_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='subscription_link',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
