# Generated by Django 5.1.6 on 2025-02-11 16:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_brand_subscription_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='newsletter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.newsletter'),
        ),
    ]
