# Generated by Django 5.1.6 on 2025-02-13 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_newsletter_campaign_alter_campaign_newsletter_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsletter',
            name='subscriber_base',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
