# Generated by Django 5.1.6 on 2025-02-13 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_remove_newsletter_xml_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsletter',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=10),
        ),
    ]
