# Generated by Django 5.1.6 on 2025-02-15 09:01

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_newsletter_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coupon_id', models.CharField(max_length=20, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('coupon_type', models.CharField(choices=[('Discount', 'Discount'), ('Cashback', 'Cashback')], max_length=50)),
                ('bill_count', models.IntegerField()),
                ('channel', models.CharField(choices=[('SMS', 'SMS'), ('WhatsApp', 'WhatsApp'), ('Email', 'Email')], max_length=50)),
                ('template_file', models.FileField(blank=True, null=True, upload_to='coupons/templates/')),
                ('newsletter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coupons', to='main.newsletter')),
            ],
        ),
    ]
