# Generated by Django 5.1.6 on 2025-02-15 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_coupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='coupon_days',
            field=models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday'), ('All Days', 'All Days')], default='All Days', max_length=100),
        ),
        migrations.AddField(
            model_name='coupon',
            name='discount_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='coupon',
            name='expiration_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='coupon_type',
            field=models.CharField(choices=[('Rs Off', 'Rs Off'), ('Percentage Off', 'Percentage Off'), ('Buy 1 Get 1', 'Buy 1 Get 1')], max_length=50),
        ),
    ]
