# Generated by Django 5.1.6 on 2025-02-15 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_coupon_coupon_days_coupon_discount_value_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='custom_coupon_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='coupon_days',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='coupon_type',
            field=models.CharField(choices=[('Flat Discount', 'Flat Discount'), ('Percentage Discount', 'Percentage Discount'), ('Bundle Offer', 'Bundle Offer'), ('Buy X Get Y', 'Buy X Get Y'), ('Custom', 'Custom')], max_length=50),
        ),
    ]
