# Generated by Django 5.1.6 on 2025-02-15 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_alter_coupon_bill_count_alter_coupon_coupon_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='buy_x',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='coupon',
            name='get_y',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
