# Generated by Django 5.1.6 on 2025-02-15 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_rename_discount_value_coupon_flat_discount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaign',
            name='channel',
        ),
    ]
