# Generated by Django 5.1.6 on 2025-02-15 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_remove_campaign_channel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GeneratedPDF',
        ),
    ]
