# Generated by Django 5.1.6 on 2025-02-15 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_trackinglink'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='template_uploaded',
            field=models.BooleanField(default=False),
        ),
    ]
