# Generated by Django 5.1.6 on 2025-02-15 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_coupon_template_uploaded'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='template_uploaded',
            field=models.BooleanField(null=True),
        ),
    ]
