# Generated by Django 5.1.6 on 2025-02-16 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_coupon_template_uploaded'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupon',
            name='template_uploaded',
        ),
    ]
