# Generated by Django 5.1.6 on 2025-02-18 02:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0032_remove_coupon_template_uploaded'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coupon',
            old_name='percentage_discount',
            new_name='discount_percentage',
        ),
        migrations.RenameField(
            model_name='coupon',
            old_name='flat_discount',
            new_name='discount_value',
        ),
        migrations.RemoveField(
            model_name='coupon',
            name='custom_coupon_type',
        ),
        migrations.RemoveField(
            model_name='coupon',
            name='newsletter',
        ),
        migrations.RemoveField(
            model_name='coupon',
            name='template_file',
        ),
        migrations.AddField(
            model_name='coupon',
            name='campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.campaign'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='bill_count',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='buy_x',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='channel',
            field=models.CharField(choices=[('SMS', 'SMS'), ('WhatsApp', 'WhatsApp'), ('Email', 'Email')], max_length=20),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='coupon_days',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='coupon_id',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='coupon_type',
            field=models.CharField(choices=[('Fixed Amount Off', 'Fixed Amount Off'), ('Percentage Discount', 'Percentage Discount'), ('Buy 1 Get 1', 'Buy 1 Get 1')], max_length=50),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='get_y',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
