# Generated by Django 5.1.6 on 2025-02-18 02:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0033_rename_percentage_discount_coupon_discount_percentage_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coupon',
            old_name='discount_value',
            new_name='flat_discount',
        ),
        migrations.RenameField(
            model_name='coupon',
            old_name='discount_percentage',
            new_name='percentage_discount',
        ),
        migrations.RemoveField(
            model_name='coupon',
            name='channel',
        ),
        migrations.AddField(
            model_name='coupon',
            name='custom_coupon_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='coupon',
            name='template_file',
            field=models.FileField(blank=True, null=True, upload_to='coupons/templates/'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='bill_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='buy_x',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='coupons', to='main.campaign'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='coupon_days',
            field=models.CharField(default='All Days', max_length=100),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='coupon_id',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='coupon_type',
            field=models.CharField(choices=[('Flat Discount', 'Flat Discount'), ('Percentage Discount', 'Percentage Discount'), ('Bundle Offer', 'Bundle Offer'), ('Buy X Get Y', 'Buy X Get Y'), ('Custom', 'Custom')], max_length=50),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='get_y',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
