# Generated by Django 5.1.6 on 2025-02-18 04:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0035_remove_newsletter_campaign_remove_newsletter_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaign',
            name='newsletter',
        ),
    ]
