# Generated by Django 5.1.6 on 2025-02-18 04:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0036_remove_campaign_newsletter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsletter',
            name='campaign_mappings',
        ),
    ]
