# Generated by Django 5.1.6 on 2025-02-19 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0038_remove_newsletter_is_frozen_remove_newsletter_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsletter',
            name='campaigns',
        ),
        migrations.RemoveField(
            model_name='newsletter',
            name='html_template',
        ),
        migrations.AddField(
            model_name='newsletter',
            name='is_frozen',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='newsletter',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='newsletter',
            name='placeholders',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='newsletter',
            name='template_content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
