# Generated by Django 5.1.6 on 2025-02-24 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0040_newsletter_campaign'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsletter',
            name='campaign',
        ),
    ]
