# Generated by Django 5.1.6 on 2025-02-27 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0041_remove_newsletter_campaign'),
    ]

    operations = [
        migrations.AddField(
            model_name='trackinglink',
            name='redeemed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='trackinglink',
            name='redeemed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
