# Generated by Django 5.1.6 on 2025-02-27 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0042_trackinglink_redeemed_trackinglink_redeemed_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='trackinglink',
            name='bill_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
